### PR TITLE
Update for CUDA 12.4.0

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/17

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Looks like we were missing `cuda-nvprune` builds

Started new builds: https://github.com/conda-forge/cuda-nvprune-feedstock/pull/5#issuecomment-1981814235

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI

**Pull request merged**
